### ISSUE TITLE
U-GAT-IT 트레이닝은 직접 A에는 아시아계 얼굴/ B에는 이말년 웹툰 얼굴을 넣어서 트레이닝시키신 건가요?

### ISSUE THREAD

**Issue by t-hyun** [bryandlee/malnyun_faces#2]
안녕하세요, 재미있게 보았습니다! U-GAT-IT이 깨지지 않고 잘 나오는 것 같은데, 거기서는 앞에서처럼 transfer learning 방식을 사용하신 것인지 아니면 처음부터 트레이닝시키신 것인지 궁금합니다!

**Comment by bryandlee** [comment]
안녕하세요. 말씀하신대로 각 데이터셋을 A,B로 설정해서 학습했고 처음부터 트레이닝하였습니다.
