### ISSUE TITLE
안녕하세요 침수자님 SeFa를 통해 manipulation 하는 방법을 공유 받고싶습니다.

### ISSUE THREAD

**Issue by isack-ml** [bryandlee/malnyun_faces#4]
안녕하세요. 침수자님 SeFa를 통해 manipulation 하는 방법을 공유 받고 싶습니다.

아시겠지만 SeFa의 경우 generator 모델의 pth확장자의 파일을 요구하는데 기존의 stylegan generator는 pkl, pt 확장자의 파일로 저장됩니다.

이러한 경우 pkl, pt 파일에서 pth확장자로 변경하는 방법을 알고 싶습니다.

감사합니다.

**Comment by bryandlee** [comment]
안녕하세요. 말씀해주신 확장자 차이가 아마도 각기 다른 구현들에서 학습한 체크포인트를 의미하신 것 같은데요,

pt - https://github.com/rosinality/stylegan2-pytorch의 경우 [여기](https://github.com/rosinality/stylegan2-pytorch/blob/master/closed_form_factorization.py)에 구현되어 있고, 

pkl -https://github.com/NVlabs/stylegan2-ada-pytorch의 경우 아래 코드를 이용하시면 됩니다.

```python
import pickle
import torch
import numpy as np

torch.set_grad_enabled(False)

with open(ckpt_path, "rb") as f:
    G = pickle.load(f)['G_ema'].cpu().float()
ckpt = G.state_dict()

weights = [v  for k, v in ckpt.items() if "affine.weight" in k and "torgb" not in k] 
weights = torch.cat(weights)
weights = weights / torch.norm(weights, dim=1, keepdim=True)
U, S, V = torch.svd(torch.cat(weights))
# i-th direction: V[:, i]

```

**Comment by leeisack** [comment]
![Screenshot from 2022-05-17 14-54-10](https://user-images.githubusercontent.com/52061393/168739005-57ede2b0-ef99-4cd0-ab10-189316476a91.png)

**Comment by isack-ml** [comment]
침수자님, 안녕하세요.

해주신 답변 잘 보았습니다.

하지만 제 궁금증이 잘 전달되지 않는 듯하여 다시금 추가 질문을 남깁니다..

sefa 에서 제공하는 colab에 checkpoints폴더에 보시면 pth의 확장자의 체크포인트를 통해 이미지 생성, 변조 기능을 수행하고 있습니다.

말씀하신바와 같이 stylegan2, stylegan-ada를 통해 학습시킨 결과물들은 pkl, pt 확장자의 체크포인트로 저장하는건 이해가 됩니다. 하지만 이를 manipulation을 하기 위해 sefa에서 사용하려면 pth로 변환해야 할 듯해 보입니다.

결과적으로  pkl에서 pt로의 변환 방법은 알겠으나 pth로 어떻게 변환 시키셨는지 궁금합니다.

![Screenshot from 2022-05-17 14-54-10](https://user-images.githubusercontent.com/52061393/168742467-86b65ec4-af7f-4984-adc4-b55011779776.png)
